# Generated by Django 4.2 on 2026-02-18 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_logement', models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('studio', 'Studio'), ('villa', 'Villa')], default='appartement', max_length=20)),
                ('adresse', models.CharField(max_length=300)),
                ('ville', models.CharField(max_length=100)),
                ('prix_par_nuit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacite', models.IntegerField(default=1)),
                ('disponible', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='logements/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
