# Generated by Django 4.2 on 2026-02-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
