# Generated by Django 4.2 on 2026-02-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type_notif',
            field=models.CharField(choices=[('nouvelle_reservation', 'Nouvelle réservation'), ('reservation_confirmee', 'Réservation confirmée'), ('reservation_refusee', 'Réservation refusée'), ('info', 'Information')], default='info', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='color',
            field=models.CharField(default='rgba(124,111,247,0.5)', max_length=50),
        ),
    ]
