# Generated by Django 4.2 on 2026-02-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification_message_notification_type_notif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='cin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CIN'),
        ),
    ]
