# Generated by Django 4.2 on 2026-02-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notification_cin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='cin',
        ),
        migrations.AddField(
            model_name='user',
            name='cin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CIN'),
        ),
    ]
