# Generated by Django 4.2 on 2026-02-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_notification_cin_user_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CIN'),
        ),
    ]
